---
abstract: 'Write Perl classes in Java.'
author:
  - 'Patrick LeBoutillier <patl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Inline-Java
no_index:
  directory:
    - t
    - inc
    - Java/*
  file:
    - Java/*.pm
requires:
  Inline: '0.68'
  Inline::C: '0.62'
  MIME::Base64: '0'
  Test: '1.13'
  perl: '5.008'
resources:
  repository: https://github.com/ingydotnet/Inline-Java
version: '0.58'
